import { HubData } from "@/type/dataType";

export const data: HubData[] = [
  {
    serial_number: 1,
    hub_name: "Shoutong Packaging Nigeria. Limited",
    address: "Along Lagos-Ibadan Expressway, Sagamu",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Paper",
  },
  {
    serial_number: 2,
    hub_name: "Metal Manufacturing Nigeria Limited",
    address:
      "2, Adlas Arisa way, Off Ijede road, Along/Sagamu-Ikorodu road, Sagamu",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 3,
    hub_name: "Nixin Paper Mill Nigeria Limited",
    address:
      "2km, After Sagamu Interchange, Along/Lagos-Ibadan Expressway, Ogere",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 4,
    hub_name: "Nitong Material Company Limited",
    address: "4km from Sagamu Interchange, Ogere/town",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 5,
    hub_name: "First Aluminium Nigeria Plc",
    address: "Ogere , Ikenne LGA",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 6,
    hub_name: "Metal World Recycling Impex Limited",
    address: "Off Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 7,
    hub_name: "Merito Worldwide Impex Limited",
    address: "Gibologi village, Konigbagbe,/Sagamu-Ikorodu road.",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 8,
    hub_name: "Metal Recycling Industry Limited",
    address: "Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 9,
    hub_name: "Everest Metal Company Limited",
    address: "Sagamu/Ikorodu Rd, Ogijo.",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 10,
    hub_name: "Standard Metallurgical Co.",
    address: "Igbafa village, Ode-Lemo road, Sagamu",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 11,
    hub_name: "Spark West Steel Industries Ltd",
    address: "Ode-Remo, Sagamu",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 12,
    hub_name: "Phoenix Steel Mills Ltd",
    address: "Shagamu- Ikorodu Rd, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 13,
    hub_name: "African Foundries",
    address: "Km 45, Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 14,
    hub_name: "Monarch Steel Nigeria Ltd",
    address: "Sagamu- Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 15,
    hub_name: "Quantum Steel Nigeria Ltd",
    address: "Off Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 16,
    hub_name: "Agriex Industries",
    address: "Ewujagun, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 17,
    hub_name: "African Non-Ferrous",
    address: "Km 45, Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 18,
    hub_name: "Math Metal Recycling Limited",
    address: "Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 19,
    hub_name: "Esteemed Multipurpose Business/Enterprises",
    address: "Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Black oil",
  },
  {
    serial_number: 20,
    hub_name: "Tech-High Profile",
    address: "Off Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Black oil",
  },
  {
    serial_number: 21,
    hub_name: "T. J. Impest Nigeria Limited",
    address: "Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Black Oil",
  },
  {
    serial_number: 22,
    hub_name: "Innoplast Nigeria Limited",
    address: "Ita-Oluwo, Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 23,
    hub_name: "Fenice Steel Nigeria Limited",
    address: "Sagamu-Ikorodu road, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 24,
    hub_name: "Gharsu Services Limited",
    address: "Km 52, Lagos- Ibadan Expressway",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 25,
    hub_name: "Lexsz Plastics Limited",
    address:
      "Km 40, Lagos- Ibadan Expressway, Kemta/Oyewolu village, via Mowe.",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 26,
    hub_name: "New Shidai Plastic Manufacturing/Limited",
    address: "Mowe Trailer Park, Along Lagos- Ibadan/Expressway",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 27,
    hub_name: "Greenbase Recycling Limited",
    address: "Ayetoro village, Mowe, Ogun State",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 28,
    hub_name: "Golden Metal Recycling Limited",
    address: "Arepo Beach, Estate road, Arepo,/Owode LGA",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 29,
    hub_name: "Prorich Products Nigeria Limited",
    address: "Km 48, Lagos- Ibadan Expressway (2km/away from RCCG Camp), Mowe",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 30,
    hub_name: "New Global Paper Limited",
    address: "Km 51, Lagos- Ibadan Expressway,/Ayetoro, Mowe",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 31,
    hub_name: "Yinfeng Recycling Company",
    address: "Lagos/Ibadan Expressway, Isheri",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 32,
    hub_name: "Global Papers Limited",
    address: "Lagos/Ibadan Expressway",
    state: "Ogun",
    lga: "Mowe-Ibafo",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 33,
    hub_name: "Dahua Paper Company Nigeria/Limited",
    address:
      "Km 14, Along Abeokuta-Lagos/Expressway, Owiwi village, Ogun State.",
    state: "Ogun",
    lga: "Abeokuta",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 34,
    hub_name: "Specialty Papers Pulp Limited",
    address: "Onigbon village, Ibefun, Ijebu-Ode/Epe road",
    state: "Ogun",
    lga: "Ijebu-Ode",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 35,
    hub_name: "Yuxin Metal Recycling Co. Limited",
    address: "Odolowu, Odogbolu",
    state: "Ogun",
    lga: "Ijebu-Ode",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 36,
    hub_name: "Verde Imparto",
    address: "40, Arobieye Mandate Ave. Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 37,
    hub_name: "Veevee Paper Products Limited",
    address: "Km 2, Ijoko road, Sango- Ota, Ogun State",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Papers",
  },
  {
    serial_number: 38,
    hub_name: "Lloyds Industries Limited",
    address: "Opposite All Over Polytechnic, Idiroko/road, Sango-Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 39,
    hub_name: "Alef Recycling Company Limited",
    address: "Block B2, Plot 1-2, Opic Estate, Agbara,/Ogun State",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 40,
    hub_name: "Green Recycling Industries Limited",
    address: "Block B2, Plot 5, Opic Estate, Agbara,/Ogun State",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 41,
    hub_name: "Terra aqua Environmental Consultancy/Limited",
    address: "Km 7 Idiroko road ,Iyana Iyesi Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 42,
    hub_name: "Priority Aluminium Limited",
    address: "Plot 5-6, Block III, Ota Industrial Estate",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 43,
    hub_name: "Balita Alloy Ltd",
    address: "306, Lagos-Abeokuta Expressway,/Ile-Epo, Sango-Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 44,
    hub_name: "Palmora Recycling Company",
    address: "Atan",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 45,
    hub_name: "Nigeria Foundries",
    address: "Lynson Chemical Avenue, Sango-Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 46,
    hub_name: "Kaizen Recycling Industries Ltd",
    address: "Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Metal",
  },
  {
    serial_number: 47,
    hub_name: "Chitra Industries Limited",
    address: "Idiroko road, Ota",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Plastics",
  },
  {
    serial_number: 48,
    hub_name: "Engee-Pet Manufacturing Limited",
    address: "Agbara road, Igbesa",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 49,
    hub_name: "T-Cynthia",
    address: "Area 5, GZI road, Iperin, OPIC Estate,/Agbara",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 50,
    hub_name: "DAI Contractor",
    address: "OPIC Industrial Estate, Agbara",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Paper",
  },
  {
    serial_number: 51,
    hub_name: "Shongai Packaging Indutries Limited",
    address: "Km 42, Lagos-Abeokuta Expressway, Ijako",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "plastic",
  },
  {
    serial_number: 52,
    hub_name: "NOC-Link Ventures",
    address: "Papalanto/Ilaro road",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 53,
    hub_name: "Juddy Beloma Industry",
    address: "Papalanto/Ilaro road",
    state: "Ogun",
    lga: "Ado-Ota",
    contact_number: "N/A",
    category: "Plastic",
  },
  {
    serial_number: 54,
    hub_name: "RecyclePoints Limited",
    address: "Alakija, Festac",
    state: "Lagos",
    lga: "Amuwo-Odofin",
    contact_number: "08098002400/07062031060",
    category: "General",
  },
  {
    serial_number: 55,
    hub_name: "Biostar Green Solutions",
    address: "32, Wale Azeez Street, Ajasa Command/White House",
    state: "Lagos",
    lga: "Ayobo-Ipaja",
    contact_number: 8150423792,
    category: "General",
  },
  {
    serial_number: 56,
    hub_name: "WATCO Global Services",
    address: "Michael Ogun Street, Off Itire Road,/Obele Oniwala, Ojuelegba",
    state: "Lagos",
    lga: "Surulere",
    contact_number: "08023199565/08065542602",
    category: "General",
  },
  {
    serial_number: 57,
    hub_name: "Wecyclers Nigeria Ltd",
    address: "Adeyole Street, Liko Bustop, Surulere",
    state: "Lagos",
    lga: "Itire Ikate",
    contact_number: "08187764011/08060368775",
    category: "Plastic",
  },
  {
    serial_number: 58,
    hub_name: "HORLAG",
    address: "Eredo, Epe",
    state: "Lagos",
    lga: "Eredo",
    contact_number: 8164484627,
    category: "General",
  },
  {
    serial_number: 59,
    hub_name: "Zebaj Recycling",
    address: "Asuku Street, Ijaiye Ojokoro",
    state: "Lagos",
    lga: "Ojokoro",
    contact_number: 8187308126,
    category: "General",
  },
  {
    serial_number: 60,
    hub_name: "Scrap Pays Technologies",
    address:
      "1 Bayo Aderiye Street, Off Jibowu Rd,/U-Turn Bus Stop, Abule Egba",
    state: "Lagos",
    lga: "Agbado Oke-Odo",
    contact_number: 8163678475,
    category: "Plastic",
  },
  {
    serial_number: 61,
    hub_name: "Green Janitors",
    address: "Azeez Ashade Close, Along Whispering/Palms, Iworo Badagry",
    state: "Lagos",
    lga: "Badagry",
    contact_number: 7062031703,
    category: "Plastic",
  },
  {
    serial_number: 62,
    hub_name: "Janirak Recyclers Global Enterprise",
    address: "28 Ojulopesi Street, Ijanikin, Badagry/Express-Way",
    state: "Lagos",
    lga: "Badagry",
    contact_number: 8024994822,
    category: "Plastic",
  },
  {
    serial_number: 63,
    hub_name: "Wecyclers Nigeria Limited",
    address: "149 Bamgbose Street, Lagos Island",
    state: "Lagos",
    lga: "Lagos Island",
    contact_number: 8127666203,
    category: "Plastic",
  },
  {
    serial_number: 64,
    hub_name: "Street Waste Company Ltd",
    address: "159, Opposite Court of Appeal, Lagos",
    state: "Lagos",
    lga: "Ikoyi-Obalende",
    contact_number: "09031108000/08038584545",
    category: "N/A",
  },
  {
    serial_number: 65,
    hub_name: "Negand Integrated Services",
    address: "Popo Williams, Lekki Scheme-2",
    state: "Lagos",
    lga: "Eti-Osa East",
    contact_number: 7033006778,
    category: "General",
  },
  {
    serial_number: 66,
    hub_name: "FAN Renewable Systems Ltd",
    address: "Isaac John Street, GRA, Ikeja",
    state: "Lagos",
    lga: "Ikeja",
    contact_number: 8034854262,
    category: "General",
  },
  {
    serial_number: 67,
    hub_name: "Monttainai Recycling",
    address: "2 Akilo Street, Ogba",
    state: "Lagos",
    lga: "Ikeja",
    contact_number: 8023143435,
    category: "Plastic",
  },
  {
    serial_number: 68,
    hub_name: "D’Monte Green",
    address: "Isheri-Olofin",
    state: "Lagos",
    lga: "Ikosi-Isheri",
    contact_number: 8023441530,
    category: "General",
  },
  {
    serial_number: 69,
    hub_name: "WRM Integrated Nig. Ltd",
    address: "Oyingbo",
    state: "Lagos",
    lga: "Lagos Mainland",
    contact_number: 8055283155,
    category: "Plastic",
  },
  {
    serial_number: 70,
    hub_name: "Cycled Technology",
    address: "Idi-Araba",
    state: "Lagos",
    lga: "Mushin",
    contact_number: 70644800800,
    category: "Plastic",
  },
  {
    serial_number: 71,
    hub_name: "Laputa Rubber Industry Limited",
    address: "2 Wonuola Street, Off Karimu Street,/Idi-Araba, Mushin",
    state: "Lagos",
    lga: "Mushin",
    contact_number: 7083808902,
    category: "Plastic",
  },
  {
    serial_number: 72,
    hub_name: "The 8088 Recycling",
    address: "3 Oyelola Street, Onipanu",
    state: "Lagos",
    lga: "Odi-Olowo",
    contact_number: 8154261752,
    category: "General",
  },
  {
    serial_number: 73,
    hub_name: "Greenhill",
    address: "Charity Bus Stop, Oshodi",
    state: "Lagos",
    lga: "Oshodi",
    contact_number: 8039377972,
    category: "General",
  },
  {
    serial_number: 74,
    hub_name: "Tricia Clarks",
    address: "Road 5, House 825, Diamond Estate/Phase 3, Igando",
    state: "Lagos",
    lga: "Igando-Ikotun",
    contact_number: 8137395510,
    category: "Plastic",
  },
  {
    serial_number: 75,
    hub_name: "Parallel Consult",
    address: "39 Jamiu Raji Street, Off Cele Egbe/Bus Stop, Ikotun",
    state: "Lagos",
    lga: "Egbe-Idimu",
    contact_number: 8188466444,
    category: "General",
  },
  {
    serial_number: 76,
    hub_name: "Ecoprune",
    address:
      "7/9 Kuburatu Agbedeyi Street, Olokode/Bus Stop, Off Nureni Yusuf Road, Kola/Alagbado",
    state: "Lagos",
    lga: "Alimosho",
    contact_number: 7064672606,
    category: "General",
  },
  {
    serial_number: 77,
    hub_name: "Denziot Integrated & Logistics Ltd",
    address: "Idi-Orogbo, Ibeju Lekki",
    state: "Lagos",
    lga: "Ibeju-Lekki",
    contact_number: 8072057267,
    category: "General",
  },
  {
    serial_number: 78,
    hub_name: "Thermal Initiative",
    address: "Chevron, Lekki",
    state: "Lagos",
    lga: "Lekki",
    contact_number: 8030720557,
    category: "General",
  },
  {
    serial_number: 79,
    hub_name: "MEDIC",
    address: "Kids Beach Garden, Oba Elegushi Beach/Road",
    state: "Lagos",
    lga: "Lekki",
    contact_number: 8033788641,
    category: "Plastic",
  },
  {
    serial_number: 80,
    hub_name: "Planet Savers",
    address: "62/64 Shagamu Road, Ikorodu",
    state: "Lagos",
    lga: "Ikorodu West",
    contact_number: "N/A",
    category: "General",
  },
  {
    serial_number: 81,
    hub_name: "Crich Weather",
    address: "4 Efunga Street, Oko Oba, Agege",
    state: "Lagos",
    lga: "Agege",
    contact_number: 8087613145,
    category: "General",
  },
  {
    serial_number: 82,
    hub_name: "Retreasure Global Solutions",
    address: "Plot 21 Amudat Close, Aguda Ogba, Lagos",
    state: "Lagos",
    lga: "Agege",
    contact_number: 8032437284,
    category: "Plastic",
  },
  {
    serial_number: 83,
    hub_name: "Waste Point",
    address: "Okerisan Village by Berger Bus-stop, Epe",
    state: "Lagos",
    lga: "Iru-VI",
    contact_number: 8098077736,
    category: "General",
  },
  {
    serial_number: 84,
    hub_name: "African Clean-Up Initiative",
    address: "3 Taiwo Odunuga Close, Off Olusegun,/Ire-Akari, Isolo",
    state: "Lagos",
    lga: "Ajeromi-Ifelodun",
    contact_number: "08021349281/08133638389",
    category: "General",
  },
  {
    serial_number: 85,
    hub_name: "Ecoplastic & Aluminum Recycling",
    address: "10/11 Sunny Smile Street, Iyano Isashi, Ojo/Lagos",
    state: "Lagos",
    lga: "Ojo",
    contact_number: 8036940416,
    category: "Plastic & Aluminum",
  },
  {
    serial_number: 86,
    hub_name: "Chanja Datti Nig. Ltd",
    address: "28 Ojulopesi Street, Ijanikin, Badagry/Express-Way",
    state: "Lagos",
    lga: "Ojo",
    contact_number: 8033458606,
    category: "General",
  },
  {
    serial_number: 87,
    hub_name: "Ecoplastic & Aluminum Recycling",
    address: "10/11 Sunny Smile Street, Iyano Isashi,/Ojo Lagos",
    state: "Lagos",
    lga: "Ojo",
    contact_number: 8036940416,
    category: "Plastic & Aluminum",
  },
  {
    serial_number: 88,
    hub_name: "Greenhill",
    address: "Aswani Market, Oshodi",
    state: "Lagos",
    lga: "Oshodi",
    contact_number: 8039377972,
    category: "General",
  },
  {
    serial_number: 89,
    hub_name: "West African ENRG",
    address: "Km 3 LASU-ISheri Road, Igando",
    state: "Lagos",
    lga: "Igando-Ikotun",
    contact_number: "08033325945/08060439591",
    category: "General",
  },
  {
    serial_number: 90,
    hub_name: "Tricia Clarks",
    address: "Road 5, House 825, Diamond Estate/Phase 3, Igando",
    state: "Lagos",
    lga: "Igando-Ikotun",
    contact_number: 8137395510,
    category: "General",
  },
  {
    serial_number: 91,
    hub_name: "FAN Renewable System Ltd.",
    address: "Omark Bus stop, Lasu Road, Igando",
    state: "Lagos",
    lga: "Igando-Ikotun",
    contact_number: 8034854262,
    category: "General",
  },
  {
    serial_number: 92,
    hub_name: "Parallel Consult",
    address: "39, Jamiu Raji Street off Cele Egbe Busstop,/Ikotun",
    state: "Lagos",
    lga: "Egbe-Idimu",
    contact_number: 8188466444,
    category: "General",
  },
  {
    serial_number: 93,
    hub_name: "Ecoprune",
    address:
      "7/9 Kuburatu Agbedeyi Street, Olokode/Bus Stop, Off Nureni Yusuf Road, Kola/Alagbado",
    state: "Lagos",
    lga: "Alimosho",
    contact_number: 7064672606,
    category: "General",
  },
  {
    serial_number: 94,
    hub_name: "Denziot Integrated & Logistics Ltd",
    address: "Idi-Orogbo, Ibeju Lekki",
    state: "Lagos",
    lga: "Ibeju-Lekki",
    contact_number: 8072057267,
    category: "General",
  },
  {
    serial_number: 95,
    hub_name: "Thermal Initiative",
    address: "Chevron, Lekki",
    state: "Lagos",
    lga: "Lekki",
    contact_number: 8187337838,
    category: "General",
  },
  {
    serial_number: 96,
    hub_name: "Wecyclers",
    address: "149, Bamgbose Street, Lagos-Island, Lagos",
    state: "Lagos",
    lga: "Lagos Island",
    contact_number: 9097439630,
    category: "General",
  },
  {
    serial_number: 97,
    hub_name: "Recycle Points",
    address:
      "No. 102 Lagos Street, Off Cemetry Street,/Ebute-Metta, Lagos Mainland",
    state: "Lagos",
    lga: "Lagos Mainland",
    contact_number: "08098002400/08053242182/07035779185/07010444052",
    category: "General",
  },
  {
    serial_number: 98,
    hub_name: "Givo Africa",
    address: "Maryland Busstop Lagos NG, Maryland/100242, Ikeja",
    state: "Lagos",
    lga: "Ikeja",
    contact_number: 8179775237,
    category: "General",
  },
  {
    serial_number: 99,
    hub_name: "Alon Green Recycling",
    address: "4 Jibowu Estate Rd. by U-turn Bus stop,/Abule Egba, Lagos",
    state: "Lagos",
    lga: "Abule Egba",
    contact_number: 9029912959,
    category: "General",
  },
  {
    serial_number: 100,
    hub_name: "Recycle Garb",
    address: "Ojerinde street, Jiboye bus-stop,/Apata-Omi road, Ibadan",
    state: "Oyo",
    lga: "Ibadan/South-West",
    contact_number: "08158562404/08160991631",
    category: "General",
  },
  {
    serial_number: 101,
    hub_name: "Eco-cyclers",
    address:
      "108 Premiere Layout, Goshen Estate,/Independence Layout Phase 2, Enugu",
    state: "Enugu",
    lga: "Enugu North",
    contact_number: 9025012196,
    category: "General",
  },
  {
    serial_number: 102,
    hub_name: "Greenaxis",
    address: "Polo Park Mall, Okpara Ave, GRA, Enugu",
    state: "Enugu",
    lga: "Enugu North",
    contact_number: "08160558771/09024411000",
    category: "General",
  },
  {
    serial_number: 103,
    hub_name: "Vicfold Recyclers",
    address: "12, Mustapha Idi Agbede, Basin Area,/Ilorin, Kwara",
    state: "Kwara",
    lga: "Ilorin South",
    contact_number: 8094865401,
    category: "General",
  },
  {
    serial_number: 104,
    hub_name: "GreenHill Recycling",
    address: "6 PFN close, Off Osolo way, Isolo, Lagos",
    state: "Lagos",
    lga: "Isolo",
    contact_number: 8121100433,
    category: "General",
  },
  {
    serial_number: 105,
    hub_name: "Ecobarter",
    address: "Pigba Kasa, Apo, Abuja",
    state: "FCT",
    lga: "Apo",
    contact_number: 8067896449,
    category: "General",
  },
  {
    serial_number: 106,
    hub_name: "Impulse Recycling",
    address: "Phase 5, Army estate, Abuja",
    state: "FCT",
    lga: "Gwagwalada",
    contact_number: 8104367636,
    category: "General",
  },
  {
    serial_number: 107,
    hub_name: "PIB Global Services",
    address: "16 Lake city plaza, Gudu, Abuja",
    state: "FCT",
    lga: "Gudu",
    contact_number: 8108759404,
    category: "General",
  },
  {
    serial_number: 108,
    hub_name: "The Upcycle Architect",
    address: "Suite 305 A2 Ebenezer place, Durumi-Area 1,/Garki, Abuja",
    state: "FCT",
    lga: "Garki",
    contact_number: 8098891993,
    category: "General",
  },
  {
    serial_number: 109,
    hub_name: "Plastcycle Waste Management/Limited",
    address: "1 Linus Ukachukwu Close, Extension,/Maitama, Abuja",
    state: "FCT",
    lga: "Maitama",
    contact_number: 8030968556,
    category: "General",
  },
  {
    serial_number: 110,
    hub_name: "Chanja Datti Co. Ltd.",
    address: "Plot #813, Durumi District Phase II, Abuja",
    state: "FCT",
    lga: "Durumi",
    contact_number: "07045550222/07069384612",
    category: "General",
  },
  {
    serial_number: 111,
    hub_name: "WastePoint Recycling Limited",
    address:
      "Suite 39/40 Bluecrest Mall, 43, Lekki-Epe /Expressway, Ajah By Fara Park Estate, /Majek Bus Stop, Abijo, Lagos State",
    state: "Lagos",
    lga: "Ajah",
    contact_number: "07000800700/08181900004",
    category: "General",
  },
  {
    serial_number: 112,
    hub_name: "Shongai Packaging Industries Limited",
    address: "Km 38, Abeokuta Expressway, Sango-Otta,/Ogun State",
    state: "Ogun",
    lga: "Sango-Otta",
    contact_number: "08086657989/08086633182",
    category: "General",
  },
  {
    serial_number: 113,
    hub_name: "Mottainai Recycling & Waste/Management",
    address: "46 Isaac John Street, Ikeja GRA, Lagos",
    state: "Lagos",
    lga: "Ikeja",
    contact_number: "07000800700/08181900004",
    category: "General",
  },
  {
    serial_number: 114,
    hub_name: "Mottainai Recycling & Waste/Management",
    address: "24, Soun Ajagungbade, New Bodija, Ibadan",
    state: "Oyo",
    lga: "Ibadan North",
    contact_number: "07000800700/08181900004",
    category: "General",
  },
  {
    serial_number: 115,
    hub_name: "Trash Monger Recycling",
    address: "Apo Primary School, Abuja",
    state: "FCT",
    lga: "Apo",
    contact_number: 8154627148,
    category: "General",
  },
  {
    serial_number: 116,
    hub_name: "Greenhill Recycling",
    address: "18b, Okeho Street, Off Ire-Akari Estate/Road, Isolo",
    state: "Lagos",
    lga: "Isolo",
    contact_number: "08121100433",
    category: "General",
  },
  {
    serial_number: 117,
    hub_name: "Metal Recycling Industries Ltd",
    address: "Shagamu-Ikorodu Road, Opposite Phoenix/Steels Mill, Ogijo",
    state: "Ogun",
    lga: "Sagamu",
    contact_number: "08077094024/08077094021",
    category: "Metal",
  },
  {
    serial_number: 118,
    hub_name: "Shongai Packaging Industry Ltd",
    address: "Km 38 Abeokuta Expressway, Sango-Otta",
    state: "Ogun",
    lga: "Sango-Otta",
    contact_number: "08129008446/08086633182",
    category: "Plastic",
  },
  {
    serial_number: 119,
    hub_name: "Wecyclers",
    address: "149 Bamgbose Street, Lagos Island",
    state: "Lagos",
    lga: "Lagos Island",
    contact_number: "08120094324/09097439630",
    category: "General",
  },
  {
    serial_number: 120,
    hub_name: "Babs Removals & Waste Services",
    address: "31A Mokola Housing Estate, Army Barracks/Road, Ibadan",
    state: "Oyo",
    lga: "Ibadan North",
    contact_number: "07058034655/08138416395",
    category: "General",
  },
  {
    serial_number: 121,
    hub_name: "Chanja Datti Co. Ltd",
    address: "Suite A11, Adjacent shop 348; Olusegun/Obasanjo block, Garki 2",
    state: "FCT",
    lga: "Garki",
    contact_number: "08182389100",
    category: "General",
  },
  {
    serial_number: 122,
    hub_name: "De Star Metals Industries",
    address: "Plot no 125/126, Ikorodu Industrial Estate,/Odogunya, Ebute",
    state: "Lagos",
    lga: "Ikorodu",
    contact_number: "08034479698/07015827654",
    category: "Aluminium",
  },
  {
    serial_number: 123,
    hub_name: "Ecofuture Nigeria",
    address: "Km 8 Sapele Road, Benin-City",
    state: "Edo",
    lga: "Oredo",
    contact_number: "08064115963/09093891964",
    category: "General",
  },
  {
    serial_number: 124,
    hub_name: "Envirocycles Ltd",
    address: "4 Creek Road, Apapa",
    state: "Lagos",
    lga: "Apapa",
    contact_number: "08033632223/08015452828",
    category: "General",
  },
  {
    serial_number: 125,
    hub_name: "Maintenance System Consultants",
    address: "1 Olusanya Street, Ilupeju",
    state: "Lagos",
    lga: "Mushin",
    contact_number: "08037051663/08037657701/08022236336",
    category: "General",
  },
  {
    serial_number: 126,
    hub_name: "Metal Circle",
    address: "14 Ope-Ewe Street, Off Agbado-Ijaiye Road,/Ifako-Ijaiye",
    state: "Lagos",
    lga: "Ifako-Ijaiye",
    contact_number: "07069130870",
    category: "Metal",
  },
  {
    serial_number: 127,
    hub_name: "Qlx Waste Management Services",
    address: "Plot 91, Riverside Park, off 5th Avenue,/Phase IV, Kubwa",
    state: "FCT",
    lga: "Kubwa",
    contact_number: "N/A",
    category: "General",
  },
  {
    serial_number: 128,
    hub_name: "RecyclePoint",
    address: "Plot 102 Lagos Street, Ebute Metta",
    state: "Lagos",
    lga: "Lagos Mainland",
    contact_number: "08053242182/08098002400/07035779185",
    category: "General",
  },
  {
    serial_number: 129,
    hub_name: "Skillsgate Ltd",
    address: "Km 62 Idiroko Road, Obasanjo bus stop,/Sango-Otta",
    state: "Ogun",
    lga: "Sango-Otta",
    contact_number: "08033809986/08025957659",
    category: "General",
  },
  {
    serial_number: 130,
    hub_name: "Takman Recycling Services",
    address: "32 Creek Road, Apapa",
    state: "Lagos",
    lga: "Apapa",
    contact_number: "09021688972",
    category: "Metal",
  },
  {
    serial_number: 131,
    hub_name: "Tongda Industries Ltd",
    address: "2 Kudirat Abiola Way, Oregun, Ikeja",
    state: "Lagos",
    lga: "Ikeja",
    contact_number: "08065860397/08072922281/08038405337",
    category: "General",
  },
  {
    serial_number: 132,
    hub_name: "Verde Impacto",
    address: "Km 40 Arobieye, Mandate Avenue, Ota",
    state: "Ogun",
    lga: "Ota",
    contact_number: "09053014482/08038164719",
    category: "General",
  },
];
